version: '3'
services:
  docs:
    build: .
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    volumes:
      - .:/docs
    environment:
      - PORT=${PORT:-8000}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
